### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yanrubi** [jpuigcerver/kaldi-decoders#2]
Hi,

I got the following error when executing make. Looks like the thread directory does not exist in Kaldi any more. Could you fix it? Thanks.

> make -C bin
> make[1]: Entering directory `/home/ubuntu/kaldi-decoders/bin'
> g++ -std=c++11 -I.. -I/home/ubuntu/kaldi/tools/openfst/include -Wno-sign-compare -Wno-unused-variable -I/home/ubuntu/kaldi/src -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ubuntu/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include -DKALDI_NO_EXPF   -c -o decode-lazylm-faster-mapped.o decode-lazylm-faster-mapped.cc
> g++  -Wl,-rpath=/home/ubuntu/kaldi/tools/openfst/lib  -rdynamic -Wl,-rpath=/home/ubuntu/kaldi/src/lib  decode-lazylm-faster-mapped.o   /home/ubuntu/kaldi/src/decoder/libkaldi-decoder.so  /home/ubuntu/kaldi/src/lat/libkaldi-lat.so  /home/ubuntu/kaldi/src/fstext/libkaldi-fstext.so  /home/ubuntu/kaldi/src/hmm/libkaldi-hmm.so  /home/ubuntu/kaldi/src/tree/libkaldi-tree.so  /home/ubuntu/kaldi/src/util/libkaldi-util.so  /home/ubuntu/kaldi/src/matrix/libkaldi-matrix.so  /home/ubuntu/kaldi/src/base/libkaldi-base.so /home/ubuntu/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -o decode-lazylm-faster-mapped
> g++ -std=c++11 -I.. -I/home/ubuntu/kaldi/tools/openfst/include -Wno-sign-compare -Wno-unused-variable -I/home/ubuntu/kaldi/src -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ubuntu/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include -DKALDI_NO_EXPF   -c -o latgen-lazylm-faster-mapped.o latgen-lazylm-faster-mapped.cc
> g++  -Wl,-rpath=/home/ubuntu/kaldi/tools/openfst/lib  -rdynamic -Wl,-rpath=/home/ubuntu/kaldi/src/lib  latgen-lazylm-faster-mapped.o   /home/ubuntu/kaldi/src/decoder/libkaldi-decoder.so  /home/ubuntu/kaldi/src/lat/libkaldi-lat.so  /home/ubuntu/kaldi/src/fstext/libkaldi-fstext.so  /home/ubuntu/kaldi/src/hmm/libkaldi-hmm.so  /home/ubuntu/kaldi/src/tree/libkaldi-tree.so  /home/ubuntu/kaldi/src/util/libkaldi-util.so  /home/ubuntu/kaldi/src/matrix/libkaldi-matrix.so  /home/ubuntu/kaldi/src/base/libkaldi-base.so /home/ubuntu/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -o latgen-lazylm-faster-mapped
> make[1]: Leaving directory `/home/ubuntu/kaldi-decoders/bin'
> make -C gmmbin
> make[1]: Entering directory `/home/ubuntu/kaldi-decoders/gmmbin'
> g++ -std=c++11 -I.. -I/home/ubuntu/kaldi/tools/openfst/include -Wno-sign-compare -Wno-unused-variable -I/home/ubuntu/kaldi/src -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ubuntu/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr/local/cuda/include -DKALDI_NO_EXPF   -c -o gmm-decode-lazylm-faster.o gmm-decode-lazylm-faster.cc
> g++  -Wl,-rpath=/home/ubuntu/kaldi/tools/openfst/lib  -rdynamic -Wl,-rpath=/home/ubuntu/kaldi/src/lib  gmm-decode-lazylm-faster.o   /home/ubuntu/kaldi/src/decoder/libkaldi-decoder.so  /home/ubuntu/kaldi/src/lat/libkaldi-lat.so  /home/ubuntu/kaldi/src/fstext/libkaldi-fstext.so  /home/ubuntu/kaldi/src/hmm/libkaldi-hmm.so  /home/ubuntu/kaldi/src/feat/libkaldi-feat.so  /home/ubuntu/kaldi/src/transform/libkaldi-transform.so  /home/ubuntu/kaldi/src/gmm/libkaldi-gmm.so  /home/ubuntu/kaldi/src/tree/libkaldi-tree.so  /home/ubuntu/kaldi/src/util/libkaldi-util.so  /home/ubuntu/kaldi/src/matrix/libkaldi-matrix.so  /home/ubuntu/kaldi/src/thread/libkaldi-thread.so  /home/ubuntu/kaldi/src/base/libkaldi-base.so /home/ubuntu/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -o gmm-decode-lazylm-faster
> g++: error: /home/ubuntu/kaldi/src/thread/libkaldi-thread.so: No such file or directory
> make[1]: *** [gmm-decode-lazylm-faster] Error 1
> make[1]: Leaving directory `/home/ubuntu/kaldi-decoders/gmmbin'
> make: *** [gmmbin] Error 2

**Comment by jpuigcerver** [comment]
Commit 088a6a9 should fix this. Thanks for reporting!
